### PR TITLE
Hyperlink DOIs to preferred resolver

### PR DESCRIPTION
**Pull request by katrinleinweber**
Same as https://github.com/PecanProject/pecan/pull/2492 ;-)

### CODE REVIEW

**Comment by infotroph** [comment]
@katrinleinweber Thanks again for the patch! This repo is updated from the PecanProject/pecan Travis job, so when your fix is merged there it will show up here automatically.

**Comment by katrinleinweber** [comment]
Cool! Sorry for overlooking that m-)

**Comment by infotroph** [comment]
Not your fault! It wasn't documented until just now.

**Comment by katrinleinweber** [comment]
I could have seen it in the `blame` or `log` view, though.

**Pull request closed without merging**
