### PR TITLE
Links not working bug fixed

### PR DESCRIPTION
**Pull request by mustafaazad03**
Issue solved [#14 ](https://github.com/PecanProject/web/issues/14)

### CODE REVIEW

**Comment by mdietze** [comment]
@robkooper is it safe to merge these fixes, or will they cause a conflict since the contents of this repo are generated programmatically from the pecan repo. I'm particularly worried about the develop branch.

@Mustafa-Azad025 either way, you'll definitely want to introduce this fix in the pecan repo itself otherwise future versions won't include this change.

**Comment by mustafaazad03** [comment]
Hey @mdietze ,
Thanks for reply , so how will I do that can u pls guide !

**Comment by mdietze** [comment]
@Mustafa-Azad025 the documentation is machine generated from the files in the book_source folder in the pecan repository. So, for example, if you want to fix something in develop/index.html in the webpage you need to fix it in https://github.com/PecanProject/pecan/blob/develop/book_source/index.Rmd (i.e. the index.Rmd file on the develop  branch)

**Comment by mustafaazad03** [comment]
Ok , thanks I will try this.

**Comment by mustafaazad03** [comment]
Hi @mdietze ,
I cloned the Pecan repo, however I'm not sure what to change in that file.

**Comment by dlebauer** [comment]
@Mustafa-Azad025 you should be able to find the same links in the .Rmd file, eg the one to join pecan slack is here: https://github.com/PecanProject/pecan/blob/e348c8981320d29bb96c4164027ad49eb9d806cd/book_source/index.Rmd#L47

**Comment by mustafaazad03** [comment]
Oh Ok thank you so much for clarifying,
I will make that correction.

**Comment by mustafaazad03** [comment]
> @Mustafa-Azad025 you should be able to find the same links in the .Rmd file, eg the one to join pecan slack is here: https://github.com/PecanProject/pecan/blob/e348c8981320d29bb96c4164027ad49eb9d806cd/book_source/index.Rmd#L47

In this I changed just the target of URL to parent i.e the link was correct but problem is of redirection of link -->
image

So how can i find in pecan repo files ?

**Comment by dlebauer** [comment]
Did you look here?
https://github.com/PecanProject/pecan/blob/e348c8981320d29bb96c4164027ad49eb9d806cd/book_source/index.Rmd#L47

**Comment by mustafaazad03** [comment]
> Did you look here? https://github.com/PecanProject/pecan/blob/e348c8981320d29bb96c4164027ad49eb9d806cd/book_source/index.Rmd#L47

yes, I look there as well.

**Pull request closed without merging**
